// List of characters names are here alongside the path for the script to help the browser locate an image of them.
const characters = [
    { image: "IMG/anko.webp" }, 
    { image: "IMG/anko2.webp" }, 
    { image: "IMG/ashura.webp" },
    { image: "IMG/baki.webp" },
    { image: "IMG/baki2.webp" },  
    { image: "IMG/chiyo.webp" }, 
    { image: "IMG/fake_choji.webp"},
    { image: "IMG/fake_choji2.webp"},
    { image: "IMG/kid_choji.webp" },
    { image: "IMG/darui.webp" },
    { image: "IMG/deidara.webp" },
    { image: "IMG/kid_gaara.webp" },
    { image: "IMG/kid_gaara2.webp" },
    { image: "IMG/gaara.webp" },
    { image: "IMG/fake_haku.webp" },
    { image: "IMG/haku.webp" },
    { image: "IMG/hashirama.webp" },
    { image: "IMG/sm_hashirama.webp" },
    { image: "IMG/edo_hashirama.webp" },
    { image: "IMG/hidan.webp" },
    { image: "IMG/fake_hinata.webp" },
    { image: "IMG/fake_hinata2.webp" },
    { image: "IMG/fake_hinata3.webp" },
    { image: "IMG/fake_hinata4.webp" },
    { image: "IMG/hinata.webp" },
    { image: "IMG/fake_hiruzen.webp" },
    { image: "IMG/fake_hiruzen2.webp" },
    { image: "IMG/hiruzen.webp" },
    { image: "IMG/hizashi1.webp" },
    { image: "IMG/hizashi11.webp" },
    { image: "IMG/hizashi2.webp" },
    { image: "IMG/hizashi22.webp" },
    { image: "IMG/fake_ino.webp" },
    { image: "IMG/fake_ino2.webp" },
    { image: "IMG/ino.webp" },
    { image: "IMG/iruka.webp" },
    { image: "IMG/fake_itachi.webp" },
    { image: "IMG/fake_itachi2.webp" },
    { image: "IMG/itachi.webp" },
    { image: "IMG/edo_itachi.webp" },
    { image: "IMG/indra.webp" },
    { image: "IMG/fake_jiraiya.webp" },
    { image: "IMG/fake_jiraiya2.webp" },
    { image: "IMG/jiraiya.webp" },
    { image: "IMG/sannin_jiraiya.webp" },
    { image: "IMG/sm_jiraiya.webp" },
    { image: "IMG/fake_jirobo.webp" },
    { image: "IMG/fake_jirobo2.webp" },
    { image: "IMG/jugo.webp" },
    { image: "IMG/kabuto.webp" },
    { image: "IMG/kabuto2.webp" },
    { image: "IMG/fake_kabuto.webp" },
    { image: "IMG/fake_kabuto2.webp" },
    { image: "IMG/kaguya.webp" },
    { image: "IMG/kid_kakashi.webp" },
    { image: "IMG/fake_kakashi.webp" },
    { image: "IMG/kakashi2.webp" },
    { image: "IMG/kakashi.webp" },
    { image: "IMG/kakashi2.webp" },
    { image: "IMG/dms_kakashi.webp" },
    { image: "IMG/kakkon.webp" },
    { image: "IMG/kakkon2.webp" },
    { image: "IMG/kakuzu.webp" },
    { image: "IMG/fake_kankuro.webp" },
    { image: "IMG/fake_kankuro2.webp" },
    { image: "IMG/fake_kankuro3.webp" },
    { image: "IMG/fake_kankuro4.webp" },
    { image: "IMG/karin.webp" },
    { image: "IMG/fake_kiba.webp" },
    { image: "IMG/fake_kiba2.webp" },
    { image: "IMG/fake_kiba3.webp" },
    { image: "IMG/fake_kiba4.webp" },
    { image: "IMG/fake_kidomaru.webp" },
    { image: "IMG/fake_kidomaru2.webp" },
    { image: "IMG/killerbee.webp" },
    { image: "IMG/kisame.webp" },
    { image: "IMG/konan.webp" },
    { image: "IMG/konohamaru.webp" },
    { image: "IMG/konohamaru1.webp" },
    { image: "IMG/konohamaru2.webp" },
    { image: "IMG/kurenai.webp" },
    { image: "IMG/kurenai2.webp" },
    { image: "IMG/kushina.webp" },
    { image: "IMG/madara.webp" },
    { image: "IMG/edo_madara.webp" },
    { image: "IMG/so6p_madara.webp" },
    { image: "IMG/mei.webp" },
    { image: "IMG/fake_guy.webp" },
    { image: "IMG/guy_.webp" },
    { image: "IMG/guy.webp" },
    { image: "IMG/guy2.webp" },
    { image: "IMG/minato.webp" },
    { image: "IMG/edo_minato.webp" },
    { image: "IMG/kcm_minato.webp" },
    { image: "IMG/mist_ninja.webp" },
    { image: "IMG/fake_naruto.webp" },
    { image: "IMG/fake_naruto2.webp" },
    { image: "IMG/kid_naruto.webp" },
    { image: "IMG/kid_naruto2.webp" },
    { image: "IMG/ot-naruto.webp" },
    { image: "IMG/naruto.webp" },
    { image: "IMG/sm_naruto.webp" },
    { image: "IMG/kcm_naruto.webp" },
    { image: "IMG/so6p_naruto.webp" },
    { image: "IMG/fv_naruto.webp" },
    { image: "IMG/last_naruto.webp" },
    { image: "IMG/nagato.webp" },
    { image: "IMG/fake_neji.webp" },
    { image: "IMG/fake_neji2.webp" },
    { image: "IMG/kid_neji.webp" },
    { image: "IMG/kid_obito.webp" },
    { image: "IMG/obito.webp" },
    { image: "IMG/so6p_obito.webp" },
    { image: "IMG/fake_orochimaru.webp" },
    { image: "IMG/fake_orochimaru2.webp" },
    { image: "IMG/orochimaru.webp" },
    { image: "IMG/sannin_orochimaru.webp" },
    { image: "IMG/pain.webp" },
    { image: "IMG/raikage.webp" },
    { image: "IMG/random.webp" },
    { image: "IMG/random1.webp" },
    { image: "IMG/random3.webp" },
    { image: "IMG/random4.webp" },
    { image: "IMG/random5.webp" },
    { image: "IMG/random6.webp" },
    { image: "IMG/random7.webp" },
    { image: "IMG/random8.webp" },
    { image: "IMG/random9.webp" },
    { image: "IMG/random10.webp" },
    { image: "IMG/random11.webp" },
    { image: "IMG/random12.webp" },
    { image: "IMG/random13.webp" },
    { image: "IMG/random14.webp" },
    { image: "IMG/random15.webp" },
    { image: "IMG/random16.webp" },
    { image: "IMG/random17.webp" },
    { image: "IMG/random18.webp" },
    { image: "IMG/random19.webp" },
    { image: "IMG/random20.webp" },
    { image: "IMG/random21.webp" },
    { image: "IMG/random22.webp" },
    { image: "IMG/random23.webp" },
    { image: "IMG/random24.webp" },
    { image: "IMG/random25.webp" },
    { image: "IMG/random26.webp" },
    { image: "IMG/random27.webp" },
    { image: "IMG/random28.webp" },
    { image: "IMG/random29.webp" },
    { image: "IMG/random30.webp" },
    { image: "IMG/random31.webp" },
    { image: "IMG/random32.webp" },
    { image: "IMG/random33.webp" },
    { image: "IMG/random34.webp" },
    { image: "IMG/random35.webp" },
    { image: "IMG/random36.webp" },
    { image: "IMG/random37.webp" },
    { image: "IMG/random38.webp" },
    { image: "IMG/fake_lee.webp" },
    { image: "IMG/kid_lee.webp" },
    { image: "IMG/rocklee.webp" },
    { image: "IMG/sai.webp" },
    { image: "IMG/fake_sakon.webp" },
    { image: "IMG/fake_sakon2.webp" },
    { image: "IMG/fake_sakura.webp" },
    { image: "IMG/fake_sakura2.webp" },
    { image: "IMG/sakura.webp" },
    { image: "IMG/sakura2.webp" },
    { image: "IMG/sasori.webp" },
    { image: "IMG/kid_sasuke.webp" },
    { image: "IMG/kid_sasuke2.webp" },
    { image: "IMG/sasuke.webp" },
    { image: "IMG/sasuke2.webp" },
    { image: "IMG/sasuke3.webp" },
    { image: "IMG/ems_sasuke.webp" },
    { image: "IMG/so6p_sasuke.webp" },
    { image: "IMG/fv_sasuke.webp" },
    { image: "IMG/shinden_sasuke.webp" },
    { image: "IMG/suigetsu.webp" },
    { image: "IMG/shibi.webp" },
    { image: "IMG/fake_shikamaru.webp" },
    { image: "IMG/fake_shikamaru2.webp" },
    { image: "IMG/shikamaru.webp" },
    { image: "IMG/fake_shino.webp" },
    { image: "IMG/shisui.webp" },
    { image: "IMG/sound_ninja.webp" },
    { image: "IMG/stone_ninja.webp" },
    { image: "IMG/fake_tayuya.webp" },
    { image: "IMG/fake_tayuya2.webp" },
    { image: "IMG/fake_temari.webp" },
    { image: "IMG/fake_temari2.webp" },
    { image: "IMG/fake_temari3.webp" },
    { image: "IMG/fake_temari4.webp" },
    { image: "IMG/fake_tenten.webp" },
    { image: "IMG/fake_tenten2.webp" },
    { image: "IMG/tenten.webp" },
    { image: "IMG/tobi.webp" },
    { image: "IMG/tobirama.webp" },
    { image: "IMG/edo_tobirama.webp" },
    { image: "IMG/yamato.webp" },
    { image: "IMG/fake_zabuza.webp" },
    { image: "IMG/fake_zabuza2.webp" },
    { image: "IMG/zabuza.webp" }
];

// Function to get a random character
function getRandomCharacter() {
    const randomIndex = Math.floor(Math.random() * characters.length);
    return characters[randomIndex];
}

// Wrap the code in a DOMContentLoaded event to ensure elements are available
document.addEventListener('DOMContentLoaded', function() {
    // Event Listener for Single Summon Button
    document.getElementById('singleSummonButton').addEventListener('click', function() {
        const summonedCharacter = getRandomCharacter();
        document.getElementById('result').innerHTML = `
            <img src="${summonedCharacter.image}" alt="Character" class="character-image">
        `;
    });

    // Event Listener for Multi Summon Button
    document.getElementById('multiSummonButton').addEventListener('click', function() {
        const summonedCharacters = [];
        for (let i = 0; i < 10; i++) {
            summonedCharacters.push(getRandomCharacter());
        }

        // Display the summoned characters in the new div
        document.getElementById('summonedCharacters').innerHTML = summonedCharacters.map(character => `
            <div class="summoned-character">
                <img src="${character.image}" alt="Character" class="character-image">
            </div>
        `).join('');
    });
});
